### ISSUE TITLE
UI Redisign Mockup

### ISSUE THREAD

**Issue by daudix-UFO** [AdwCustomizerTeam/design#2]
Mockup for UI redisign 

# V1

![Adwaita Manager V1](https://user-images.githubusercontent.com/77155297/181392263-97eab96f-d386-4d12-95bb-0571b3411796.png)

# V2

![Adwaita Manager V2](https://user-images.githubusercontent.com/77155297/181852906-4ab61ab7-7a86-4c72-9d22-e4a6d0c27312.png)

_[📎 SVG, PNG & All Future Versions](https://drive.google.com/drive/folders/1a7SDgbVaGE9GnsEW2udspE6YyXrFrNnK?usp=sharing)_

**Comment by 0xMRTT** [comment]
You can just add in the repo instead of an issue ?

**Comment by daudix-UFO** [comment]
Pardon.
